// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/processing": {
    params: {};
  };
  "/app/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app" | "/app/processing" | "/app/dashboard";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/app.processing.tsx": {
    id: "routes/app.processing";
    page: "/app/processing";
  };
  "routes/app.dashboard.tsx": {
    id: "routes/app.dashboard";
    page: "/app/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.processing": typeof import("./app/routes/app.processing.tsx");
  "routes/app.dashboard": typeof import("./app/routes/app.dashboard.tsx");
};